### ISSUE TITLE
DRF + Custom jwt auth

### ISSUE THREAD

**Issue by ShreehariVaasishta** [jazzband/django-debug-toolbar#1423]
Not able to understand the usage of this tool with drf when im using jwt authentication.

**Comment by tim-schilling** [comment]
Can you be more specific regarding the issue with the toolbar? The following questions are a good starting point, but the more information you can provide the easier it will be for someone to help.

- What does your setup look like?
- What error is occurring?
- What is happening that you don't expect?
- What isn't happening that you expected to?

**Comment by ShreehariVaasishta** [comment]
When I'm using JWT authentication (using pyjwt) for building APIs with DRF, I cannot pass the token from the browser(drf provides a UI for each APIs) as it will throw an invalid token error(no way to pass jwt). Hence I cannot make any requests. Without which this toolbar won't work. 
![DRF + JWT](https://user-images.githubusercontent.com/37337599/101731234-5733d780-3ae1-11eb-9ec0-c87391e81fb0.png)

Hope this gave you an idea of my issue.

**Comment by jeffxor** [comment]
@tim-schilling, I think the question is how you add a header to the request being made so that this can be used with DRF+JWT. I don't see any third-party plugins that add this support.

Most applications these days are built using DRF and JWT for authentication, so adding support for this would be very helpful to a larger audience.  

This could be as simple as adding the ability to apply headers to their request, similar to how you handle POST/PATCH bodies. Also, people may use headers in general in their requests for other reasons. This feature would solve more than one problem.

**Comment by jeffxor** [comment]
Let me know if I should open a new issue to request support to add headers to requests

**Comment by tim-schilling** [comment]
@jeffxor I'm confused. I don't understand why authentication is causing problems here. Can you help me understand why you need to authenticate to view the toolbar on your local machine?
