### ISSUE TITLE
Django debug toolbar is not showing in the production AWS Ec2 Ubuntu server

### ISSUE THREAD

**Issue by kaushik-ganesan** [jazzband/django-debug-toolbar#1428]
I have a django API connected with Apache webserver and mod_wsgi. When I call the public DNS/IP address of the Ubuntu-20.4 EC2 instance, the django API is triggered. I have installed the Django debug tool using this documentation (https://django-debug-toolbar.readthedocs.io/en/latest/installation.html). How can I make the debug toolbar show when I call the public DNS of the EC2 instance from my local computer?

**Comment by tim-schilling** [comment]
Did you configure the [`INTERNAL_IPS`](https://django-debug-toolbar.readthedocs.io/en/latest/installation.html#configuring-internal-ips) to include your own IP?

**Comment by kaushik-ganesan** [comment]
@tim-schilling Do you mean the IP address of my local computer? If yes, I have not included that. INTERNAL_IPS = ['0.0.0.0:80']

**Comment by tim-schilling** [comment]
I suspect that should work if you have `DEBUG=True`. The toolbar tries to prevent developers from enabling it on a production server because it will expose sensitive information to users. I'd recommend cloning your production environment to a local or development area rather than using the toolbar there. However, if you insist you can change the [`SHOW_TOOLBAR_CALLBACK` setting](https://django-debug-toolbar.readthedocs.io/en/latest/configuration.html#show-toolbar-callback) to force the toolbar to show.

**Comment by kaushik-ganesan** [comment]
@tim-schilling The problem was with the type of response I was returning. Seems like the django debug toolbar doesn't showup when you are returning plain JsonResponse/HttpResponse. Instead, you have to send a response with the <body> tag.

**Comment by tim-schilling** [comment]
Correct. That's part of the `INSERT_BEFORE` configuration.

**Comment by tim-schilling** [comment]
Closing the issue as it seems it has been resolved. Let me know if that's not the case.
