### ISSUE TITLE
Incorrect template definition

### ISSUE THREAD

**Issue by ktyz1992** [jazzband/django-debug-toolbar#1458]
In my case, I called the render function but forgot to return it. Further down the code, there is another call to the render function that returns. As a result, as expected, the template is output from the returned render function, but the template for the first render function without returning was specified in the DjDT panel.

**Comment by tim-schilling** [comment]
I'm closing this as a won't fix. The reason being is that the templates panel currently works by using the `template_rendered` signal/receiver. I don't see a clear path to determining which template was used when being passed to the response. Additionally, if someone is using `render_to_string` for sending emails or other messages, we'd want to capture those rather than only the templates that were used in the response.
