### ISSUE TITLE
Include instructions on APP_DIRS in Prerequisites docs

### ISSUE THREAD

**Issue by timohermans** [jazzband/django-debug-toolbar#1491]
So I was having `TemplateDoesNotExist` errors when trying to set up everything.

It took me some time to realize that for this package to work, you need to have `APP_DIRS: True` for debug_toolbar to include its templates in the projects.

Perhaps it's a good idea to include this in the documentation?

**Comment by tim-schilling** [comment]
Yeah as a temporary solution that'd be good to put in the troubleshooting space. However, ideally the toolbar would work without it and if that's not possible, it'd fail gracefully and log a warning.

**Comment by matthiask** [comment]
The `django.contrib.sitemaps` app also requires `"APP_DIRS": True`; we could have a look there how `"APP_DIRS": False` is handled. I couldn't find a check or anything (I didn't look long) so maybe it's enough to document the expectation that templates can be loaded from app dirs. 

(I haven't used `"APP_DIRS": False` or anything equivalent ever since beginning to use Django before 1.0, maybe this is exotic enough that we could simply ignore it. At least if it proves too much work to add a system check or something.)

**Comment by tim-schilling** [comment]
I don't see any checks or error handling in sitemaps. And I think attempting to hijack the settings to make it work is a poor idea.
