### ISSUE TITLE
Log when form is using file fields without proper enctype attribute on the form.

### ISSUE THREAD

**Issue by tim-schilling** [jazzband/django-debug-toolbar#1682]
One of the issues that can trip up new developers is the fact that forms require `enctype="multipart/form-data"` when there's a file being uploaded. If a developer doesn't know this, it can be hard to track down. I think it'd be reasonable to have the toolbar inspect the loaded HTML content and inspect it for invalid configurations. The first of which being a `<input type="file" ..> />` in a form that isn't defined as `<form enctype="multipart/form-data">`.

**Comment by bkdekoning** [comment]
Hi all,

I've taken a [shot](https://github.com/bkdekoning/django-debug-toolbar/commit/d19bf7b93617de98b3a4f8b54efec60ea446d413) at the issue and am curious to hear what you think about my approach. 

Since there is no warnings/alerts panel yet (as discussed in issue [#1845](https://github.com/jazzband/django-debug-toolbar/issues/1845)), I figured the Templates panel would be the most sensible place to implement is.

What I've done is subclass Python's HTML parser and added a function called `check_invalid_file_form_configuration` in `panels/templates/panel.py`. The function checks all forms for a file input type and, if it exists, checks if the form has encoding type multipart/form-data. If it does not, it warns the user in the Templates panel by passing the error message to `record_stats`. I've added two tests and checked that the test suite passes for all compatible versions of Django and Python through Tox. 

In lieu of having a dedicated warnings/alerts panel, I am wondering whether it would be helpful to add a little notification flag (perhaps in nav_title, or nav_subtitle) to indicate that something is up.

Happy to hear any and all thoughts!

**Comment by matthiask** [comment]
> In lieu of having a dedicated warnings/alerts panel, I am wondering whether it would be helpful to add a little notification flag (perhaps in nav_title, or nav_subtitle) to indicate that something is up.

Yeah, I think we definitely would need some sort of notification for things like these. I would certainly miss the alert if it was buried somewhere in a panel.

I have briefly looked at the code and think that it makes sense. Feel free to open a pull request without prior discussion, then we can let GitHub run the testsuite and maybe also add some review comments if necessary, directly on the PR!

**Comment by bkdekoning** [comment]
That makes sense. I can create an alerts panel as part of this issue, keeping in mind that it needs to be able to accommodate issues such as #1435 and #1845.

Thanks for the heads-up about setting the form's encoding type on the submit input. I'll make sure to include that in the checks and see if there are any other gotchas.

**Comment by tim-schilling** [comment]
Eesh, another way to associate a form and input: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#form
