### ISSUE TITLE
Using a cached loader results in W006 warning

### ISSUE THREAD

**Issue by nstuardod** [jazzband/django-debug-toolbar#1704]
After updating from 3.2.1 to 3.7, running `./manage.py check` while using a cached loader results in a W006 warning.

I'm working on a project using pypugjs which uses a config like this:
```python
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                ...
            ],
            "loaders": [
                (
                    "pypugjs.ext.django.Loader",
                    (
                        "django.template.loaders.filesystem.Loader",
                        "django.template.loaders.app_directories.Loader",
                    ),
                )
            ],
            "builtins": [
                "pypugjs.ext.django.templatetags",
            ],
        },
    },
]
```

But it also reproduces with
```python
"loaders": [
    (
        "django.template.loaders.cached.Loader",
        (
            "django.template.loaders.filesystem.Loader",
            "django.template.loaders.app_directories.Loader",
        ),
    )
],
```

**Comment by matthiask** [comment]
Django automatically adds the cached loader when `DEBUG` is `False` (resp. `TEMPLATES[...]["OPTIONS"]["debug"]` is `False` which in turn defaults to `DEBUG`. So in the case of the second example the warning points towards a simplification of the setting.

I'm not sure what to do here. Silencing the warning is completely fine if you know what you're doing. And we haven't gotten any reports about the toolbar being unable to render since introducing the warning so it's definitely a net plus for us. But of course we shouldn't annoy advanced users either.

Maybe the language around system checks could generally make it clearer that silencing checks *may* be totally fine?

**Comment by nstuardod** [comment]
OK, the warning makes complete sense for the second example.
As our project used .pug templates, we configured TEMPLATES as [defined on the documentation](https://github.com/kakulukia/pypugjs/blob/master/docs/installation.rst#django-111). Since `pypugjs.ext.django.Loader` is a subclass of `cached.Loader`, a list of loaders has to be defined.

I think the problem might be caused due the way `check_template_config` checks settings, as it does not check for tuples inside `TEMPLATES[...][OPTIONS]["loaders"]`.

Despite the warning, my app works fine, and I will consider silencing the message as a workaround.
