### ISSUE TITLE
Add Turbo/HTMX script templatetag?

### ISSUE THREAD

**Issue by joshuadavidthomas** [jazzband/django-debug-toolbar#1762]
Would it be useful for debug toolbar to include the scripts from issue https://github.com/jazzband/django-debug-toolbar/issues/1179 as a templatetag?

**Comment by tim-schilling** [comment]
Hi Josh! I'm not sure. This is one of those integration processes that I'm not 100% on what would be the best for most developers.

That said, it might be good for the toolbar to simply listen to that event and also log something to the console that it occurred. Then provide a way for it to be overridden (maybe via a template override or setting).

**Comment by matthiask** [comment]
I could imagine that having those functions by default would be useful for some users while being problematic for very few, since the events are namespaced and everything. If we were to ship them by default we should put them into a file of their own (`integrations.js` comes to mind?) and allow an easy switch to opt out of loading this file. We could then stuff all known and future integrations in there and tell people to deactivate the integrations file if it proves problematic or if they want to change their integration somewhat?

**Comment by joshuadavidthomas** [comment]
Not sure when this was added, but [this section on working with htmx](https://django-debug-toolbar.readthedocs.io/en/latest/tips.html#id1) from the docs solved my problem.
