### ISSUE TITLE
Django logging not working when djdt is enabled

### ISSUE THREAD

**Issue by forrestkouakou** [jazzband/django-debug-toolbar#1814]
I recently noticed that django default logging is not working when I enable djdt.
django-debug-toolbar==4.1.0
Django==4.2.3

Is it possible to have SQL pannel and logging for sql queries work together?

Without djdt
<img width="919" alt="Screenshot 2023-07-10 at 01 00 07" src="https://github.com/jazzband/django-debug-toolbar/assets/10248817/2207582e-01ad-4f9c-bbfd-acd1b48d9839">

With djdt
<img width="914" alt="Screenshot 2023-07-10 at 01 02 08" src="https://github.com/jazzband/django-debug-toolbar/assets/10248817/d5967fc9-2db4-4efd-9b79-3cf153e1bd71">

**Comment by tim-schilling** [comment]
Hi @forrestkouakou, can you create a reproducible environment for this?

**Comment by dannosaur** [comment]
I've just dug deep into django's guts to figure out why our console logging isn't working either. It looks like it's caused by the DjDTCursorWrapper (`debug_toolbar/panels/sql/tracking:wrap_cursor()`) overriding the default CursorDebugWrapper that django installs based on `settings.DEBUG` or an option set somehow to force it. When `wrap_cursor()` is called by djdt, it's returning an instance of `NormalCursorWrapper` which eventually extends `CursorWrapper` (not `CursorDebugWrapper` where the logging functions are).

My guess is that the resolution to this is that `DjDTCursorWrapper` needs to be mindful of what cursor django has installed, and if it's installed `CursorDebugWrapper` instead of `CursorWrapper` then it should inherit that instead. Something can probably modify `DjDTCursorWrapper.__bases__` or use a function in the class inheritance instead in order to dynamically inherit the correct cursor wrapper class.

**Comment by living180** [comment]
@tim-schilling based on this would you support a revert of e7575e87dc9e2d2560b87d6fd5a123b9398cbd34?

**Comment by tim-schilling** [comment]
@dannosaur thank you for that investigation! That's super helpful. Do you have a reproducible use case?

@living180 I think I'm on board for a revert, though I'd prefer to roll forward a fix.

**Comment by dannosaur** [comment]
@tim-schilling yes, I can reproduce the issue in my project.

**Comment by tim-schilling** [comment]
@dannosaur Sorry, I meant can you create a way for me to reproduce the error so that I can investigate and attempt a fix?

**Comment by dannosaur** [comment]
@tim-schilling lol, sorry! I'll try and put something together quickly tomorrow that reproduces the issue. I don't think it's a complex setup though - django 4.2, any version of psycopg (2 or 3), and djdt 4.1. Leave it with me, I'll post back tomorrow with a git repo.

**Comment by tim-schilling** [comment]
No worries. I can set up postgres on my end. Having the ability to pull a repo, set up a database and reproduce the problem makes this much, much easier to investigate. Otherwise I'm attempting random things to try to reproduce the behavior. I appreciate your work on this so far, thank you!

**Comment by dannosaur** [comment]
@tim-schilling here you go: https://github.com/dannosaur/djdttest

The django admin is installed with a user. Login `dan`/`password`. Observe the terminal running runserver - there should be some queries printed directed at `auth_user` table. In settings.py I put a `DISABLE_PANELS` section with a commented out item. If you uncomment that line (158) and reload the admin user list page, you'll see the SQL query in the console.

LMK if you need anything else, happy to help!

**Comment by tim-schilling** [comment]
Thank you @dannosaur, I was able to reproduce this.

**Comment by tim-schilling** [comment]
Can folks test their project against https://github.com/jazzband/django-debug-toolbar/pull/1820 to confirm that works?

**Comment by dannosaur** [comment]
@tim-schilling confirmed working now in my project.
