### ISSUE TITLE
SQL panel output not encoded properly

### ISSUE THREAD

**Issue by jgbishop** [jazzband/django-debug-toolbar#884]
I'm seeing the following output in my SQL panel using 1.5:

![bug](https://cloud.githubusercontent.com/assets/4210087/18923025/d6c60fae-8578-11e6-99d7-ffce68b6999d.png)

Note how HTML elements aren't being encoded properly. I'm running this with Django 1.8.14 on Python 3.5. All other panels in the toolbar appear to render correctly.

**Comment by jgbishop** [comment]
There appears to be a bug somewhere in the `BoldKeywordFilter` class, as I can get readable output if I disable that call (line 25 in panels\sql\utils.py).

**Comment by jgbishop** [comment]
Upon further inspection, I don't think the bug is down in `BoldKeywordFilter` after all. Somehow, the SQL is getting sanitized twice (I think). Not sure why.

**Comment by oppianmatt** [comment]
I was getting this too, and also there was no sql stacktrace. Turns out I was using this middleware:

```
debug_panel.middleware.DebugPanelMiddleware
```

changed it back to normal one and it was fine.

It's related to the issue if the middleware has been installed twice (then the sql will be encoded twice and there will be no stacktrace for sql). This can also happen if you manually install the middleware but leave patch settings to true.

**Comment by oppianmatt** [comment]
if you are using debug panel, this is the issue there https://github.com/recamshak/django-debug-panel/issues/17

**Comment by jgbishop** [comment]
Interesting. I also am using the DebugPanelMiddleware, and I hadn't thought of it being the culprit. Good catch! I'll close this, since this seems to be an issue with the Panel, not the toolbar.
