### ISSUE TITLE
Can't uninstall dev version in virtual env

### ISSUE THREAD

**Issue by SalahAdDin** [jazzband/django-debug-toolbar#888]
Hi,

I installed the dev version in my virtualenv environment, i want delete it and install the new release version, but i have this problem:

``` bash
Exception:
Traceback (most recent call last):
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/pip/commands/uninstall.py", line 76, in run
    requirement_set.uninstall(auto_confirm=options.yes)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/pip/req/req_set.py", line 336, in uninstall
    req.uninstall(auto_confirm=auto_confirm)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/pip/req/req_install.py", line 687, in uninstall
    '(at %s)' % (link_pointer, self.name, dist.location)
AssertionError: Egg-link /home/salahaddin/Proyectos/uzman/src/django-debug-toolbar does not match installed location of django-debug-toolbar (at /home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages)
```

Do anyone know how solve it?

**Comment by matthiask** [comment]
I don't know how to solve that in a general way. 

If I move myself into a corner using virtualenv/pip I mostly just delete the virtualenv and create a new one and reinstall everything. Since the advent of [wheels](https://pip.pypa.io/en/stable/reference/pip_wheel/) the pain has gone because C extensions do not have to be recompiled all the time, so I'd just do that.

If there's an issue specific to django-debug-toolbar (and not just virtualenv/pip handling) feel free to reopen the issue and clarify.

**Comment by SalahAdDin** [comment]
Is not good idea install developer egg, i have to clear all virtual env and reinstall all packages.

**Comment by matthiask** [comment]
Switching between released versions and source checkouts is not always straightforward. There are good reasons for doing it, but source checkouts should not generally be used (esp. not in production)

All of this is unimportant though when you can easily rebuild the whole virtualenv.
