### ISSUE TITLE
RemovedInDjango20Warning: from django.core.urlresolvers import resolve

### ISSUE THREAD

**Issue by narenchoudhary** [jazzband/django-debug-toolbar#898]
Django==1.10.3
django-debug-toolbar==1.6

I'm getting following `RemovedInDjango20Warning` warning:

    .../venv/local/lib/python2.7/site-packages/debug_toolbar/panels/request.py:3:
    RemovedInDjango20Warning: 
    Importing from django.core.urlresolvers is deprecated in favor of django.urls.
    from django.core.urlresolvers import resolve

(*stacktrace has been wraped for presentation*)

The change was added way back Django in Jan 2016 [here](https://github.com/django/django/pull/5898).

**Comment by matthiask** [comment]
Thanks for the report! This issue is already fixed in the master branch and will be part of the next release. (https://github.com/jazzband/django-debug-toolbar/commit/d974015467e01a659ab83dd4ffb8ae3cfb3c55ee)

Jan 2016 is not that long ago seeing that we're still supporting Django 1.8, released in spring 2015.
