### ISSUE TITLE
It doesnot count query while making query from another thread

### ISSUE THREAD

**Issue by amankumarjain** [jazzband/django-debug-toolbar#932]
How to debug database query when query is executed from separate thread.

**Comment by diegobill** [comment]
Same problem +1

**Comment by matthiask** [comment]
This may be because Django ensures that all database connections are cursors differ between threads. 

I think it may be very hard to implement cross-thread tracking of queries; there probably aren't easy ways to determine the originating thread in the general case; patching the `threading` module may work but maybe it won't. Also, the work would probably have to be redone for the async case. So, if anyone has a good idea how to implement this, please contribute (code or ideas) but for now I'm leaning towards closing this as not planned.
