### ISSUE TITLE
debug-toolbar 1.8 still extremely slow with django 1.11

### ISSUE THREAD

**Issue by jribbens** [jazzband/django-debug-toolbar#943]
Upgrading from 1.7 to 1.8 fixed the problem initially, but then when I edited a model admin to have two different inlines, the admin page for editing that model started taking 24 seconds. Without debug-toolbar installed it takes 3 seconds (which itself is very slow, I don't know why).

Obviously this report is a little vague, if you would like further information please let me know what you need.

**Comment by kezabelle** [comment]
If at all possible, can you answer any of the following:
- How many templates are being reported as rendered?
- How many SQL queries are being reported as executed?
- Are you using a custom `DEBUG_TOOLBAR_CONFIG`? If so, can you provide it?
- Can you provide example reported template contexts, with any sensitive values suitably fiddled with?
- How big is the HTTP response, as reported by either runserver's output or your browser's dev tools?
- How long does the same request take with Django<1.11 and debug_toolbar<1.8 (I realise that's a bigger ask potentially, but it would be useful to set a baseline), and do any of the query/template counts change notably?

**Comment by jribbens** [comment]
Ok, when adding a new instance of the model (i.e. all data blank and no instances of the inline models):

- Templates rendered: 13 (admin/change_form.html, admin/base_site.html, admin/base.html, admin/includes/fieldset.html, admin/edit_inline/tabular.html, admin/edit_inline/stacked.html, admin/includes/fieldset.html, admin/includes/fieldset.html, admin/edit_inline/stacked.html, admin/includes/fieldset.html, admin/includes/fieldset.html, admin/submit_line.html, admin/prepopulated_fields_js.html)
- SQL queries executed: 1,770 in 1,102ms (1,768 duplicates)
- `DEBUG_TOOLBAR_CONFIG` is not set
- I've put the `admin/change_form.html` context (which was the first one listed by debug_toolbar) here: https://gist.github.com/jribbens/0b3b02f1ddc831cad51899b12e2d0fcc. Obviously, there were 12 other contexts also.
- HTML is 131kB (compressed to 16.4kB)
- With django 1.10.7 and debug_toolbar 1.7 it still takes 24.3 seconds (versus 2.63 seconds with django 1.10.7 and no debug_toolbar). So I guess this isn't a regression, it's just a pre-existing problem! Number of templates is 18 and SQL queries are 1,776 (1,773 duplicates).

I don't know if 1,770 queries is a lot. The number decreases to 2 queries if I remove one of the admin-inlines, of a model that looks like this:

```python
class Note(Model):
    """A textual note about something."""
    company = ForeignKey(Company, null=True, on_delete=CASCADE)
    office = ForeignKey(Office, null=True, on_delete=CASCADE)
    source = URLField(blank=True)
    note = TextField()
```

(`company` is the main model that `Note` is an inline of, `office` is another model, most of the queries seem to be fetching `office__country`, where `country` is itself a `ForeignKey` reference to a table of all 249 countries.)

**Comment by jribbens** [comment]
Update: if I add a `Manager` to the `Office` model:
```python

**Comment by jribbens** [comment]
If I add a custom manager to the `Office` model:
```python
class OfficeManager(Manager):
    """Manager for Office objects."""
    # pylint: disable=too-few-public-methods
    def get_queryset(self):
        """Returns a new QuerySet object."""
        return super().get_queryset().select_related("country")
```
then it reduces to 3 queries and 1 second, even with debug_toolbar running. I guess maybe the issue was simply expected performance overhead from debug_toolbar when there are lots of queries?

**Comment by kezabelle** [comment]
Executing lots of queries has always taken up a substantial amount of time (even if the queries themselves report as having been a fraction of the total time) due (I think) to a combination of walking stack frames and whatever else happens in the panel's recording. I expect that there are potentially improvements to be made there, but mostly it's something that's been lived with.

In a way, it's a useful feature as it often lets you know you're doing a whole bunch of queries where you probably don't want to, and usually can be mitigated by sensible use of select/prefetch related. It's a valid "complaint" though.

**Comment by tolomea** [comment]
@jribbens 
You might find this useful if you haven't found it already https://docs.djangoproject.com/en/1.11/ref/contrib/admin/#django.contrib.admin.ModelAdmin.list_select_related

**Comment by interDist** [comment]
I have a similar – though much more acute – problem. Recently upgraded to Django 1.11.5 and Debug-Toolbar 1.8. Without DT, the admin site is a blaze and runs smoothly; yet as soon as DT is enabled, the `add` and `change` pages within the admin become painfully slow and some cannot be used at all, timing out and resulting in `Unable to connect: can't establish a connection to the server`. What’s curious is that it happens only on the modification pages, not for the object list pages.

~~▪ ▪ ▪ ▪~~ ~~▪ ▪ ▪ ▪~~ ~~▪ ▪ ▪ ▪~~ ~~▪ ▪ ▪ ▪~~ ~~▪ ▪ ▪ ▪~~ ~~▪ ▪ ▪ ▪~~ ~~▪ ▪ ▪ ▪~~ ~~▪ ▪ ▪ ▪~~ ~~▪ ▪ ▪ ▪~~ ~~▪ ▪ ▪ ▪~~ ~~▪ ▪ ▪ ▪~~ ~~▪ ▪ ▪ ▪~~ ~~▪ ▪ ▪ ▪~~

Here are the statistics for a sample `add` page:
* Templates rendered: 659 (most are from _django/forms/widgets_)
* SQL queries executed: 5 queries in 27 ms
* `DEBUG_TOOLBAR_CONFIG` has only one entry, `'JQUERY_URL': '/static/js/jquery.min.js'`
* Reported template context example: 
```python
    django.template.context_processors.csrf
        {'csrf_token': <SimpleLazyObject: 'cs0UU90QIBby0JTYRQa2CPAbhq1RpI370HhXKtAkZ2NPfgiE9Sj4cqk0RMWRTrph'>}
    django.template.context_processors.debug
        {'debug': True, 'sql_queries': <function debug.<locals>.<lambda> at 0x9e744d1c>}
    django.template.context_processors.request
        {'request': <WSGIRequest: GET '/admin/my_app/my_object_a/add/'>}
    django.contrib.auth.context_processors.auth
        {'user': <SimpleLazyObject: <User: g>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x9e75246c>}
    django.contrib.messages.context_processors.messages
        {'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x9e7400ec>, 'DEFAULT_MESSAGE_LEVELS': {'ERROR': 40, 'SUCCESS': 25, 'INFO': 20, 'WARNING': 30, 'DEBUG': 10}}
    postman.context_processors.inbox
        {'postman_unread_count': 0}
```
* HTTP response: html 49 kb, total 1667 kb
* Browser timing for response: **176091 ms**
* Downgrading to Django 1.10.8 (with DT still 1.8), the same request times 799 ms for response, queries count is 7, templates count is **_12_**, html size 48 kb.

~~▪ ▪ ▪ ▪~~ ~~▪ ▪ ▪ ▪~~ ~~▪ ▪ ▪ ▪~~ ~~▪ ▪ ▪ ▪~~ ~~▪ ▪ ▪ ▪~~ ~~▪ ▪ ▪ ▪~~ ~~▪ ▪ ▪ ▪~~ ~~▪ ▪ ▪ ▪~~ ~~▪ ▪ ▪ ▪~~ ~~▪ ▪ ▪ ▪~~ ~~▪ ▪ ▪ ▪~~ ~~▪ ▪ ▪ ▪~~ ~~▪ ▪ ▪ ▪~~

Here are the statistics for a sample `change` page (different model):
* Templates rendered: 564 (most are from _django/forms/widgets_)
* SQL queries executed: 6 queries in 24 ms
* `DEBUG_TOOLBAR_CONFIG` has only one entry, `'JQUERY_URL': '/static/js/jquery.min.js'`
* Reported template context example: 
```python
    django.template.context_processors.csrf
        {'csrf_token': <SimpleLazyObject: 'KXLtCoKp454hMtSQCYrLJcMO5LCUYmiyyc2wsIkTlwGy10hwU0ANjNwDF7xUs5EI'>}
    django.template.context_processors.debug
        {'debug': True, 'sql_queries': <function debug.<locals>.<lambda> at 0xb46dfcd4>}
    django.template.context_processors.request
        {'request': <WSGIRequest: GET '/admin/my_app/my_object_b/3/change/'>}
    django.contrib.auth.context_processors.auth
        {'user': <SimpleLazyObject: <User: g>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0xb46f768c>}
    django.contrib.messages.context_processors.messages
        {'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0xb52825ec>, 'DEFAULT_MESSAGE_LEVELS': {'ERROR': 40, 'SUCCESS': 25, 'INFO': 20, 'WARNING': 30, 'DEBUG': 10}}
    postman.context_processors.inbox
        {'postman_unread_count': 0}
```
* HTTP response: html 30 kb, total 629 kb
* Browser timing for response: **154299 ms**
* Downgrading to Django 1.10.8 (with DT still 1.8), the same request times 472 ms for response, queries count is 6, templates count is **_7_**, html size 29 kb.

~~▪ ▪ ▪ ▪~~ ~~▪ ▪ ▪ ▪~~ ~~▪ ▪ ▪ ▪~~ ~~▪ ▪ ▪ ▪~~ ~~▪ ▪ ▪ ▪~~ ~~▪ ▪ ▪ ▪~~ ~~▪ ▪ ▪ ▪~~ ~~▪ ▪ ▪ ▪~~ ~~▪ ▪ ▪ ▪~~ ~~▪ ▪ ▪ ▪~~ ~~▪ ▪ ▪ ▪~~ ~~▪ ▪ ▪ ▪~~ ~~▪ ▪ ▪ ▪~~

In some cases I get the error

    File "/root/.virtualenvs/devel/lib/python3.4/site-packages/debug_toolbar/panels/templates/panel.py", line 118, in _store_template_info
    MemoryError
    Killed

And then the Django development server dies. In some other cases my machine completely crashes (probably because of memory overflow or corruption).

So, it seems that the sole culprit is the changed mechanism for form widget rendering in Django 11: previously everything was done via Python (inlined templates with string substitution), now every widget has its own template. DT is probably not optimised for this change and the sheer number of templates freaks it out...

**Comment by shudson250** [comment]
I just had a 22minute page render for a single instance of a model - 170 SQL queries completed in 161.52ms, the rest of the time is a total mystery to me. I'm not totally sure what data is useful so I'll start with the basics:
Versions
 python: 3.5.0
 django 1.11
 debug_toolbar: 1.6
 postgres db with pysopg2 as engine, all on local computer (SSD)

37 static files - half are grappelli admin ui

Signals: 7 receivers of 12 signals

Templates (WHOA me thinks this is the issue) 1578
-1576 are django/forms/widgets/*
   - 781 django/forms/widgets/attrs.html
   - 771 django/forms/widgets/select_option.html

The model is as such:
place = FK
owner = FK
renter = FK
subs = M2M
event = One2One
... other fields of Int/Char/Decimal/Bool types
@property
def start(obj): return obj.event.start.astimezone(tz_conversion)
def end(obj): return obj.event.end.astimezone

No idea why the widget templates were pulled in so many times, but there we have it - a 22 minute load to show one model.
Disabling DT brings page load to 1s
